dependencies:
  - name: "nlohmann_json"
    url: "https://github.com/nlohmann/json.git"
  - name: "btwxt"
  - name: "courier"
    url: "https://github.com/bigladder/courier.git"
  - name: "fmt"
    url: "https://github.com/fmtlib/fmt.git"